### PR TITLE
Grunt supports "clean" target

### PR DESCRIPTION
**Pull request by silkimen**
I have added an target that is run on msbuild "clean", because I'm using grunt for building and cleaning my project. Maybe it's useful for others, too.

### CODE REVIEW

**Comment by silkimen** [comment]
But wait I've missed backwards compatibility. Let me fix that tomorrow and I'll send you another pull request.

**Comment by silkimen** [comment]
Ok now it's also backwards compatible. I have done same changes for MSBuild.Gulp and included changes in README.

**Comment by kmees** [comment]
Grunt does work for `Clean` and `Build` seperately but when I do a `Rebuild` only the `Clean` task gets executed. I think it would be better to leave to `RunGulp`/`RunGrunt` Task as is and just add a seperate clean task for each.

**Comment by silkimen** [comment]
Oh yes, you're right. I have the same problem with `Rebuild`. But I don't know how to fix that. I don't believe that it will work for `Rebuild`, if I write an separate clean task. Do you got any idea? How do you clean your grunt / gulp projects?

**Comment by kmees** [comment]
I usually cleanup with a batch script in the postbuild event or as the first subtask of my buildtask (so it's not actually tied to the VS clean command). I'll give the separate clean task a try later sine I generally like the idea and see how it goes

**Comment by kmees** [comment]
The [MSBuild Documentation](https://msdn.microsoft.com/en-us/library/ee216359.aspx) for Targets states that 

> A target is never run twice during a build, even if a subsequent target in the build depends on it. Once a target has been run, its contribution to the build is complete.

That's the reason why the `RunGulp` task is only run once during a rebuild. Creating two seperate run tasks should solve the issue

**Pull request closed without merging**
